In [1]:
import gymnasium as gym

In [2]:
env = gym.make("InvertedPendulum-v4")

In [3]:
env.reset()

(array([ 0.00728757, -0.00892222,  0.00554112, -0.00158215]), {})

In [5]:
env.step([1.580921])

(array([ 0.01804054, -0.0334382 ,  0.53064823, -1.21187962]),
 1.0,
 False,
 False,
 {})

In [6]:
import torch

In [8]:
x = torch.tensor([1,2,3,4])

In [10]:
torch.roll(x,-1)

tensor([2, 3, 4, 1])